###############################################################################
#
# Build script for project
#
###############################################################################

###############################################################################
# SOURCE VARS
EXECUTABLE	:= simpleCUDPP

CCFILES :=	scan_gold.cpp
CUFILES :=	simpleCUDPP.cu

INCLUDES := -I../../cudpp/include

USECUDPP := 1

include ../../linux_build/common.mk

