# Generated by CMake 2.8.7

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target cudpp
ADD_LIBRARY(cudpp SHARED IMPORTED)

# Create imported target cudpp_hash
ADD_LIBRARY(cudpp_hash SHARED IMPORTED)

# Import target "cudpp" for configuration ""
SET_PROPERTY(TARGET cudpp APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(cudpp PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "/usr/local/cuda-5.5/lib64/libcudart.so;/usr/lib/libcuda.so"
  IMPORTED_LOCATION_NOCONFIG "/home/laura/cudpp/lib/libcudpp.so"
  IMPORTED_SONAME_NOCONFIG "libcudpp.so"
  )

# Import target "cudpp_hash" for configuration ""
SET_PROPERTY(TARGET cudpp_hash APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(cudpp_hash PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "/usr/local/cuda-5.5/lib64/libcudart.so;/usr/lib/libcuda.so;cudpp"
  IMPORTED_LOCATION_NOCONFIG "/home/laura/cudpp/lib/libcudpp_hash.so"
  IMPORTED_SONAME_NOCONFIG "libcudpp_hash.so"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
